
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace VikkiSoft_BLL.DAL
{
	public abstract class _Category : SqlClientEntity
	{
		public _Category()
		{
			this.QuerySource = "Category";
			this.MappingName = "Category";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadAllCategory]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int CategoryID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.CategoryID, CategoryID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadCategoryByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter CategoryID
			{
				get
				{
					return new SqlParameter("@CategoryID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name
			{
				get
				{
					return new SqlParameter("@Name", SqlDbType.VarChar, 255);
				}
			}
			
			public static SqlParameter Name_en
			{
				get
				{
					return new SqlParameter("@Name_en", SqlDbType.VarChar, 255);
				}
			}
			
			public static SqlParameter Name_pl
			{
				get
				{
					return new SqlParameter("@Name_pl", SqlDbType.NVarChar, 255);
				}
			}
			
			public static SqlParameter CategoryContent
			{
				get
				{
					return new SqlParameter("@CategoryContent", SqlDbType.VarChar, 2147483647);
				}
			}
			
			public static SqlParameter CategoryContent_en
			{
				get
				{
					return new SqlParameter("@CategoryContent_en", SqlDbType.VarChar, 2147483647);
				}
			}
			
			public static SqlParameter CategoryContent_pl
			{
				get
				{
					return new SqlParameter("@CategoryContent_pl", SqlDbType.VarChar, 2147483647);
				}
			}
			
			public static SqlParameter RoomCategoryID
			{
				get
				{
					return new SqlParameter("@RoomCategoryID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Keywords
			{
				get
				{
					return new SqlParameter("@Keywords", SqlDbType.VarChar, 250);
				}
			}
			
			public static SqlParameter Keywords_en
			{
				get
				{
					return new SqlParameter("@Keywords_en", SqlDbType.VarChar, 250);
				}
			}
			
			public static SqlParameter Keywords_pl
			{
				get
				{
					return new SqlParameter("@Keywords_pl", SqlDbType.NVarChar, 250);
				}
			}
			
			public static SqlParameter Description
			{
				get
				{
					return new SqlParameter("@Description", SqlDbType.VarChar, 200);
				}
			}
			
			public static SqlParameter Description_en
			{
				get
				{
					return new SqlParameter("@Description_en", SqlDbType.VarChar, 200);
				}
			}
			
			public static SqlParameter Description_pl
			{
				get
				{
					return new SqlParameter("@Description_pl", SqlDbType.NVarChar, 200);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string CategoryID = "CategoryID";
            public const string Name = "Name";
            public const string Name_en = "Name_en";
            public const string Name_pl = "Name_pl";
            public const string CategoryContent = "CategoryContent";
            public const string CategoryContent_en = "CategoryContent_en";
            public const string CategoryContent_pl = "CategoryContent_pl";
            public const string RoomCategoryID = "RoomCategoryID";
            public const string Keywords = "Keywords";
            public const string Keywords_en = "Keywords_en";
            public const string Keywords_pl = "Keywords_pl";
            public const string Description = "Description";
            public const string Description_en = "Description_en";
            public const string Description_pl = "Description_pl";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[CategoryID] = _Category.PropertyNames.CategoryID;
					ht[Name] = _Category.PropertyNames.Name;
					ht[Name_en] = _Category.PropertyNames.Name_en;
					ht[Name_pl] = _Category.PropertyNames.Name_pl;
					ht[CategoryContent] = _Category.PropertyNames.CategoryContent;
					ht[CategoryContent_en] = _Category.PropertyNames.CategoryContent_en;
					ht[CategoryContent_pl] = _Category.PropertyNames.CategoryContent_pl;
					ht[RoomCategoryID] = _Category.PropertyNames.RoomCategoryID;
					ht[Keywords] = _Category.PropertyNames.Keywords;
					ht[Keywords_en] = _Category.PropertyNames.Keywords_en;
					ht[Keywords_pl] = _Category.PropertyNames.Keywords_pl;
					ht[Description] = _Category.PropertyNames.Description;
					ht[Description_en] = _Category.PropertyNames.Description_en;
					ht[Description_pl] = _Category.PropertyNames.Description_pl;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string CategoryID = "CategoryID";
            public const string Name = "Name";
            public const string Name_en = "Name_en";
            public const string Name_pl = "Name_pl";
            public const string CategoryContent = "CategoryContent";
            public const string CategoryContent_en = "CategoryContent_en";
            public const string CategoryContent_pl = "CategoryContent_pl";
            public const string RoomCategoryID = "RoomCategoryID";
            public const string Keywords = "Keywords";
            public const string Keywords_en = "Keywords_en";
            public const string Keywords_pl = "Keywords_pl";
            public const string Description = "Description";
            public const string Description_en = "Description_en";
            public const string Description_pl = "Description_pl";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[CategoryID] = _Category.ColumnNames.CategoryID;
					ht[Name] = _Category.ColumnNames.Name;
					ht[Name_en] = _Category.ColumnNames.Name_en;
					ht[Name_pl] = _Category.ColumnNames.Name_pl;
					ht[CategoryContent] = _Category.ColumnNames.CategoryContent;
					ht[CategoryContent_en] = _Category.ColumnNames.CategoryContent_en;
					ht[CategoryContent_pl] = _Category.ColumnNames.CategoryContent_pl;
					ht[RoomCategoryID] = _Category.ColumnNames.RoomCategoryID;
					ht[Keywords] = _Category.ColumnNames.Keywords;
					ht[Keywords_en] = _Category.ColumnNames.Keywords_en;
					ht[Keywords_pl] = _Category.ColumnNames.Keywords_pl;
					ht[Description] = _Category.ColumnNames.Description;
					ht[Description_en] = _Category.ColumnNames.Description_en;
					ht[Description_pl] = _Category.ColumnNames.Description_pl;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string CategoryID = "s_CategoryID";
            public const string Name = "s_Name";
            public const string Name_en = "s_Name_en";
            public const string Name_pl = "s_Name_pl";
            public const string CategoryContent = "s_CategoryContent";
            public const string CategoryContent_en = "s_CategoryContent_en";
            public const string CategoryContent_pl = "s_CategoryContent_pl";
            public const string RoomCategoryID = "s_RoomCategoryID";
            public const string Keywords = "s_Keywords";
            public const string Keywords_en = "s_Keywords_en";
            public const string Keywords_pl = "s_Keywords_pl";
            public const string Description = "s_Description";
            public const string Description_en = "s_Description_en";
            public const string Description_pl = "s_Description_pl";

		}
		#endregion		
		
		#region Properties
	
		public virtual int CategoryID
	    {
			get
	        {
				return base.Getint(ColumnNames.CategoryID);
			}
			set
	        {
				base.Setint(ColumnNames.CategoryID, value);
			}
		}

		public virtual string Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Name, value);
			}
		}

		public virtual string Name_en
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name_en);
			}
			set
	        {
				base.Setstring(ColumnNames.Name_en, value);
			}
		}

		public virtual string Name_pl
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name_pl);
			}
			set
	        {
				base.Setstring(ColumnNames.Name_pl, value);
			}
		}

		public virtual string CategoryContent
	    {
			get
	        {
				return base.Getstring(ColumnNames.CategoryContent);
			}
			set
	        {
				base.Setstring(ColumnNames.CategoryContent, value);
			}
		}

		public virtual string CategoryContent_en
	    {
			get
	        {
				return base.Getstring(ColumnNames.CategoryContent_en);
			}
			set
	        {
				base.Setstring(ColumnNames.CategoryContent_en, value);
			}
		}

		public virtual string CategoryContent_pl
	    {
			get
	        {
				return base.Getstring(ColumnNames.CategoryContent_pl);
			}
			set
	        {
				base.Setstring(ColumnNames.CategoryContent_pl, value);
			}
		}

		public virtual int RoomCategoryID
	    {
			get
	        {
				return base.Getint(ColumnNames.RoomCategoryID);
			}
			set
	        {
				base.Setint(ColumnNames.RoomCategoryID, value);
			}
		}

		public virtual string Keywords
	    {
			get
	        {
				return base.Getstring(ColumnNames.Keywords);
			}
			set
	        {
				base.Setstring(ColumnNames.Keywords, value);
			}
		}

		public virtual string Keywords_en
	    {
			get
	        {
				return base.Getstring(ColumnNames.Keywords_en);
			}
			set
	        {
				base.Setstring(ColumnNames.Keywords_en, value);
			}
		}

		public virtual string Keywords_pl
	    {
			get
	        {
				return base.Getstring(ColumnNames.Keywords_pl);
			}
			set
	        {
				base.Setstring(ColumnNames.Keywords_pl, value);
			}
		}

		public virtual string Description
	    {
			get
	        {
				return base.Getstring(ColumnNames.Description);
			}
			set
	        {
				base.Setstring(ColumnNames.Description, value);
			}
		}

		public virtual string Description_en
	    {
			get
	        {
				return base.Getstring(ColumnNames.Description_en);
			}
			set
	        {
				base.Setstring(ColumnNames.Description_en, value);
			}
		}

		public virtual string Description_pl
	    {
			get
	        {
				return base.Getstring(ColumnNames.Description_pl);
			}
			set
	        {
				base.Setstring(ColumnNames.Description_pl, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_CategoryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CategoryID) ? string.Empty : base.GetintAsString(ColumnNames.CategoryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CategoryID);
				else
					this.CategoryID = base.SetintAsString(ColumnNames.CategoryID, value);
			}
		}

		public virtual string s_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name) ? string.Empty : base.GetstringAsString(ColumnNames.Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name);
				else
					this.Name = base.SetstringAsString(ColumnNames.Name, value);
			}
		}

		public virtual string s_Name_en
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name_en) ? string.Empty : base.GetstringAsString(ColumnNames.Name_en);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name_en);
				else
					this.Name_en = base.SetstringAsString(ColumnNames.Name_en, value);
			}
		}

		public virtual string s_Name_pl
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name_pl) ? string.Empty : base.GetstringAsString(ColumnNames.Name_pl);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name_pl);
				else
					this.Name_pl = base.SetstringAsString(ColumnNames.Name_pl, value);
			}
		}

		public virtual string s_CategoryContent
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CategoryContent) ? string.Empty : base.GetstringAsString(ColumnNames.CategoryContent);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CategoryContent);
				else
					this.CategoryContent = base.SetstringAsString(ColumnNames.CategoryContent, value);
			}
		}

		public virtual string s_CategoryContent_en
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CategoryContent_en) ? string.Empty : base.GetstringAsString(ColumnNames.CategoryContent_en);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CategoryContent_en);
				else
					this.CategoryContent_en = base.SetstringAsString(ColumnNames.CategoryContent_en, value);
			}
		}

		public virtual string s_CategoryContent_pl
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CategoryContent_pl) ? string.Empty : base.GetstringAsString(ColumnNames.CategoryContent_pl);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CategoryContent_pl);
				else
					this.CategoryContent_pl = base.SetstringAsString(ColumnNames.CategoryContent_pl, value);
			}
		}

		public virtual string s_RoomCategoryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RoomCategoryID) ? string.Empty : base.GetintAsString(ColumnNames.RoomCategoryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RoomCategoryID);
				else
					this.RoomCategoryID = base.SetintAsString(ColumnNames.RoomCategoryID, value);
			}
		}

		public virtual string s_Keywords
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Keywords) ? string.Empty : base.GetstringAsString(ColumnNames.Keywords);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Keywords);
				else
					this.Keywords = base.SetstringAsString(ColumnNames.Keywords, value);
			}
		}

		public virtual string s_Keywords_en
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Keywords_en) ? string.Empty : base.GetstringAsString(ColumnNames.Keywords_en);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Keywords_en);
				else
					this.Keywords_en = base.SetstringAsString(ColumnNames.Keywords_en, value);
			}
		}

		public virtual string s_Keywords_pl
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Keywords_pl) ? string.Empty : base.GetstringAsString(ColumnNames.Keywords_pl);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Keywords_pl);
				else
					this.Keywords_pl = base.SetstringAsString(ColumnNames.Keywords_pl, value);
			}
		}

		public virtual string s_Description
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Description) ? string.Empty : base.GetstringAsString(ColumnNames.Description);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Description);
				else
					this.Description = base.SetstringAsString(ColumnNames.Description, value);
			}
		}

		public virtual string s_Description_en
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Description_en) ? string.Empty : base.GetstringAsString(ColumnNames.Description_en);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Description_en);
				else
					this.Description_en = base.SetstringAsString(ColumnNames.Description_en, value);
			}
		}

		public virtual string s_Description_pl
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Description_pl) ? string.Empty : base.GetstringAsString(ColumnNames.Description_pl);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Description_pl);
				else
					this.Description_pl = base.SetstringAsString(ColumnNames.Description_pl, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter CategoryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CategoryID, Parameters.CategoryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name_en
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name_en, Parameters.Name_en);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name_pl
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name_pl, Parameters.Name_pl);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CategoryContent
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CategoryContent, Parameters.CategoryContent);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CategoryContent_en
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CategoryContent_en, Parameters.CategoryContent_en);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CategoryContent_pl
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CategoryContent_pl, Parameters.CategoryContent_pl);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RoomCategoryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RoomCategoryID, Parameters.RoomCategoryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Keywords
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Keywords, Parameters.Keywords);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Keywords_en
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Keywords_en, Parameters.Keywords_en);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Keywords_pl
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Keywords_pl, Parameters.Keywords_pl);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Description
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Description, Parameters.Description);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Description_en
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Description_en, Parameters.Description_en);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Description_pl
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Description_pl, Parameters.Description_pl);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter CategoryID
		    {
				get
		        {
					if(_CategoryID_W == null)
	        	    {
						_CategoryID_W = TearOff.CategoryID;
					}
					return _CategoryID_W;
				}
			}

			public WhereParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public WhereParameter Name_en
		    {
				get
		        {
					if(_Name_en_W == null)
	        	    {
						_Name_en_W = TearOff.Name_en;
					}
					return _Name_en_W;
				}
			}

			public WhereParameter Name_pl
		    {
				get
		        {
					if(_Name_pl_W == null)
	        	    {
						_Name_pl_W = TearOff.Name_pl;
					}
					return _Name_pl_W;
				}
			}

			public WhereParameter CategoryContent
		    {
				get
		        {
					if(_CategoryContent_W == null)
	        	    {
						_CategoryContent_W = TearOff.CategoryContent;
					}
					return _CategoryContent_W;
				}
			}

			public WhereParameter CategoryContent_en
		    {
				get
		        {
					if(_CategoryContent_en_W == null)
	        	    {
						_CategoryContent_en_W = TearOff.CategoryContent_en;
					}
					return _CategoryContent_en_W;
				}
			}

			public WhereParameter CategoryContent_pl
		    {
				get
		        {
					if(_CategoryContent_pl_W == null)
	        	    {
						_CategoryContent_pl_W = TearOff.CategoryContent_pl;
					}
					return _CategoryContent_pl_W;
				}
			}

			public WhereParameter RoomCategoryID
		    {
				get
		        {
					if(_RoomCategoryID_W == null)
	        	    {
						_RoomCategoryID_W = TearOff.RoomCategoryID;
					}
					return _RoomCategoryID_W;
				}
			}

			public WhereParameter Keywords
		    {
				get
		        {
					if(_Keywords_W == null)
	        	    {
						_Keywords_W = TearOff.Keywords;
					}
					return _Keywords_W;
				}
			}

			public WhereParameter Keywords_en
		    {
				get
		        {
					if(_Keywords_en_W == null)
	        	    {
						_Keywords_en_W = TearOff.Keywords_en;
					}
					return _Keywords_en_W;
				}
			}

			public WhereParameter Keywords_pl
		    {
				get
		        {
					if(_Keywords_pl_W == null)
	        	    {
						_Keywords_pl_W = TearOff.Keywords_pl;
					}
					return _Keywords_pl_W;
				}
			}

			public WhereParameter Description
		    {
				get
		        {
					if(_Description_W == null)
	        	    {
						_Description_W = TearOff.Description;
					}
					return _Description_W;
				}
			}

			public WhereParameter Description_en
		    {
				get
		        {
					if(_Description_en_W == null)
	        	    {
						_Description_en_W = TearOff.Description_en;
					}
					return _Description_en_W;
				}
			}

			public WhereParameter Description_pl
		    {
				get
		        {
					if(_Description_pl_W == null)
	        	    {
						_Description_pl_W = TearOff.Description_pl;
					}
					return _Description_pl_W;
				}
			}

			private WhereParameter _CategoryID_W = null;
			private WhereParameter _Name_W = null;
			private WhereParameter _Name_en_W = null;
			private WhereParameter _Name_pl_W = null;
			private WhereParameter _CategoryContent_W = null;
			private WhereParameter _CategoryContent_en_W = null;
			private WhereParameter _CategoryContent_pl_W = null;
			private WhereParameter _RoomCategoryID_W = null;
			private WhereParameter _Keywords_W = null;
			private WhereParameter _Keywords_en_W = null;
			private WhereParameter _Keywords_pl_W = null;
			private WhereParameter _Description_W = null;
			private WhereParameter _Description_en_W = null;
			private WhereParameter _Description_pl_W = null;

			public void WhereClauseReset()
			{
				_CategoryID_W = null;
				_Name_W = null;
				_Name_en_W = null;
				_Name_pl_W = null;
				_CategoryContent_W = null;
				_CategoryContent_en_W = null;
				_CategoryContent_pl_W = null;
				_RoomCategoryID_W = null;
				_Keywords_W = null;
				_Keywords_en_W = null;
				_Keywords_pl_W = null;
				_Description_W = null;
				_Description_en_W = null;
				_Description_pl_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter CategoryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CategoryID, Parameters.CategoryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name_en
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name_en, Parameters.Name_en);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name_pl
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name_pl, Parameters.Name_pl);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CategoryContent
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CategoryContent, Parameters.CategoryContent);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CategoryContent_en
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CategoryContent_en, Parameters.CategoryContent_en);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CategoryContent_pl
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CategoryContent_pl, Parameters.CategoryContent_pl);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RoomCategoryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RoomCategoryID, Parameters.RoomCategoryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Keywords
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Keywords, Parameters.Keywords);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Keywords_en
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Keywords_en, Parameters.Keywords_en);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Keywords_pl
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Keywords_pl, Parameters.Keywords_pl);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Description
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Description, Parameters.Description);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Description_en
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Description_en, Parameters.Description_en);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Description_pl
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Description_pl, Parameters.Description_pl);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter CategoryID
		    {
				get
		        {
					if(_CategoryID_W == null)
	        	    {
						_CategoryID_W = TearOff.CategoryID;
					}
					return _CategoryID_W;
				}
			}

			public AggregateParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public AggregateParameter Name_en
		    {
				get
		        {
					if(_Name_en_W == null)
	        	    {
						_Name_en_W = TearOff.Name_en;
					}
					return _Name_en_W;
				}
			}

			public AggregateParameter Name_pl
		    {
				get
		        {
					if(_Name_pl_W == null)
	        	    {
						_Name_pl_W = TearOff.Name_pl;
					}
					return _Name_pl_W;
				}
			}

			public AggregateParameter CategoryContent
		    {
				get
		        {
					if(_CategoryContent_W == null)
	        	    {
						_CategoryContent_W = TearOff.CategoryContent;
					}
					return _CategoryContent_W;
				}
			}

			public AggregateParameter CategoryContent_en
		    {
				get
		        {
					if(_CategoryContent_en_W == null)
	        	    {
						_CategoryContent_en_W = TearOff.CategoryContent_en;
					}
					return _CategoryContent_en_W;
				}
			}

			public AggregateParameter CategoryContent_pl
		    {
				get
		        {
					if(_CategoryContent_pl_W == null)
	        	    {
						_CategoryContent_pl_W = TearOff.CategoryContent_pl;
					}
					return _CategoryContent_pl_W;
				}
			}

			public AggregateParameter RoomCategoryID
		    {
				get
		        {
					if(_RoomCategoryID_W == null)
	        	    {
						_RoomCategoryID_W = TearOff.RoomCategoryID;
					}
					return _RoomCategoryID_W;
				}
			}

			public AggregateParameter Keywords
		    {
				get
		        {
					if(_Keywords_W == null)
	        	    {
						_Keywords_W = TearOff.Keywords;
					}
					return _Keywords_W;
				}
			}

			public AggregateParameter Keywords_en
		    {
				get
		        {
					if(_Keywords_en_W == null)
	        	    {
						_Keywords_en_W = TearOff.Keywords_en;
					}
					return _Keywords_en_W;
				}
			}

			public AggregateParameter Keywords_pl
		    {
				get
		        {
					if(_Keywords_pl_W == null)
	        	    {
						_Keywords_pl_W = TearOff.Keywords_pl;
					}
					return _Keywords_pl_W;
				}
			}

			public AggregateParameter Description
		    {
				get
		        {
					if(_Description_W == null)
	        	    {
						_Description_W = TearOff.Description;
					}
					return _Description_W;
				}
			}

			public AggregateParameter Description_en
		    {
				get
		        {
					if(_Description_en_W == null)
	        	    {
						_Description_en_W = TearOff.Description_en;
					}
					return _Description_en_W;
				}
			}

			public AggregateParameter Description_pl
		    {
				get
		        {
					if(_Description_pl_W == null)
	        	    {
						_Description_pl_W = TearOff.Description_pl;
					}
					return _Description_pl_W;
				}
			}

			private AggregateParameter _CategoryID_W = null;
			private AggregateParameter _Name_W = null;
			private AggregateParameter _Name_en_W = null;
			private AggregateParameter _Name_pl_W = null;
			private AggregateParameter _CategoryContent_W = null;
			private AggregateParameter _CategoryContent_en_W = null;
			private AggregateParameter _CategoryContent_pl_W = null;
			private AggregateParameter _RoomCategoryID_W = null;
			private AggregateParameter _Keywords_W = null;
			private AggregateParameter _Keywords_en_W = null;
			private AggregateParameter _Keywords_pl_W = null;
			private AggregateParameter _Description_W = null;
			private AggregateParameter _Description_en_W = null;
			private AggregateParameter _Description_pl_W = null;

			public void AggregateClauseReset()
			{
				_CategoryID_W = null;
				_Name_W = null;
				_Name_en_W = null;
				_Name_pl_W = null;
				_CategoryContent_W = null;
				_CategoryContent_en_W = null;
				_CategoryContent_pl_W = null;
				_RoomCategoryID_W = null;
				_Keywords_W = null;
				_Keywords_en_W = null;
				_Keywords_pl_W = null;
				_Description_W = null;
				_Description_en_W = null;
				_Description_pl_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "InsertCategory]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.CategoryID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "UpdateCategory]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "DeleteCategory]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.CategoryID);
			p.SourceColumn = ColumnNames.CategoryID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.CategoryID);
			p.SourceColumn = ColumnNames.CategoryID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name);
			p.SourceColumn = ColumnNames.Name;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name_en);
			p.SourceColumn = ColumnNames.Name_en;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name_pl);
			p.SourceColumn = ColumnNames.Name_pl;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CategoryContent);
			p.SourceColumn = ColumnNames.CategoryContent;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CategoryContent_en);
			p.SourceColumn = ColumnNames.CategoryContent_en;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CategoryContent_pl);
			p.SourceColumn = ColumnNames.CategoryContent_pl;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RoomCategoryID);
			p.SourceColumn = ColumnNames.RoomCategoryID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Keywords);
			p.SourceColumn = ColumnNames.Keywords;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Keywords_en);
			p.SourceColumn = ColumnNames.Keywords_en;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Keywords_pl);
			p.SourceColumn = ColumnNames.Keywords_pl;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Description);
			p.SourceColumn = ColumnNames.Description;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Description_en);
			p.SourceColumn = ColumnNames.Description_en;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Description_pl);
			p.SourceColumn = ColumnNames.Description_pl;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
