
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace VikkiSoft_BLL.DAL
{
	public abstract class _Room : SqlClientEntity
	{
		public _Room()
		{
			this.QuerySource = "Room";
			this.MappingName = "Room";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadAllRoom]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int RoomID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.RoomID, RoomID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadRoomByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter RoomID
			{
				get
				{
					return new SqlParameter("@RoomID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Number
			{
				get
				{
					return new SqlParameter("@Number", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter RoomCategoryID
			{
				get
				{
					return new SqlParameter("@RoomCategoryID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Price
			{
				get
				{
					return new SqlParameter("@Price", SqlDbType.Money, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string RoomID = "RoomID";
            public const string Number = "Number";
            public const string RoomCategoryID = "RoomCategoryID";
            public const string Price = "Price";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[RoomID] = _Room.PropertyNames.RoomID;
					ht[Number] = _Room.PropertyNames.Number;
					ht[RoomCategoryID] = _Room.PropertyNames.RoomCategoryID;
					ht[Price] = _Room.PropertyNames.Price;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string RoomID = "RoomID";
            public const string Number = "Number";
            public const string RoomCategoryID = "RoomCategoryID";
            public const string Price = "Price";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[RoomID] = _Room.ColumnNames.RoomID;
					ht[Number] = _Room.ColumnNames.Number;
					ht[RoomCategoryID] = _Room.ColumnNames.RoomCategoryID;
					ht[Price] = _Room.ColumnNames.Price;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string RoomID = "s_RoomID";
            public const string Number = "s_Number";
            public const string RoomCategoryID = "s_RoomCategoryID";
            public const string Price = "s_Price";

		}
		#endregion		
		
		#region Properties
	
		public virtual int RoomID
	    {
			get
	        {
				return base.Getint(ColumnNames.RoomID);
			}
			set
	        {
				base.Setint(ColumnNames.RoomID, value);
			}
		}

		public virtual string Number
	    {
			get
	        {
				return base.Getstring(ColumnNames.Number);
			}
			set
	        {
				base.Setstring(ColumnNames.Number, value);
			}
		}

		public virtual int RoomCategoryID
	    {
			get
	        {
				return base.Getint(ColumnNames.RoomCategoryID);
			}
			set
	        {
				base.Setint(ColumnNames.RoomCategoryID, value);
			}
		}

		public virtual decimal Price
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.Price);
			}
			set
	        {
				base.Setdecimal(ColumnNames.Price, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_RoomID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RoomID) ? string.Empty : base.GetintAsString(ColumnNames.RoomID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RoomID);
				else
					this.RoomID = base.SetintAsString(ColumnNames.RoomID, value);
			}
		}

		public virtual string s_Number
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Number) ? string.Empty : base.GetstringAsString(ColumnNames.Number);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Number);
				else
					this.Number = base.SetstringAsString(ColumnNames.Number, value);
			}
		}

		public virtual string s_RoomCategoryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RoomCategoryID) ? string.Empty : base.GetintAsString(ColumnNames.RoomCategoryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RoomCategoryID);
				else
					this.RoomCategoryID = base.SetintAsString(ColumnNames.RoomCategoryID, value);
			}
		}

		public virtual string s_Price
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Price) ? string.Empty : base.GetdecimalAsString(ColumnNames.Price);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Price);
				else
					this.Price = base.SetdecimalAsString(ColumnNames.Price, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter RoomID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RoomID, Parameters.RoomID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Number
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Number, Parameters.Number);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RoomCategoryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RoomCategoryID, Parameters.RoomCategoryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Price
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Price, Parameters.Price);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter RoomID
		    {
				get
		        {
					if(_RoomID_W == null)
	        	    {
						_RoomID_W = TearOff.RoomID;
					}
					return _RoomID_W;
				}
			}

			public WhereParameter Number
		    {
				get
		        {
					if(_Number_W == null)
	        	    {
						_Number_W = TearOff.Number;
					}
					return _Number_W;
				}
			}

			public WhereParameter RoomCategoryID
		    {
				get
		        {
					if(_RoomCategoryID_W == null)
	        	    {
						_RoomCategoryID_W = TearOff.RoomCategoryID;
					}
					return _RoomCategoryID_W;
				}
			}

			public WhereParameter Price
		    {
				get
		        {
					if(_Price_W == null)
	        	    {
						_Price_W = TearOff.Price;
					}
					return _Price_W;
				}
			}

			private WhereParameter _RoomID_W = null;
			private WhereParameter _Number_W = null;
			private WhereParameter _RoomCategoryID_W = null;
			private WhereParameter _Price_W = null;

			public void WhereClauseReset()
			{
				_RoomID_W = null;
				_Number_W = null;
				_RoomCategoryID_W = null;
				_Price_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter RoomID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RoomID, Parameters.RoomID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Number
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Number, Parameters.Number);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RoomCategoryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RoomCategoryID, Parameters.RoomCategoryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Price
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Price, Parameters.Price);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter RoomID
		    {
				get
		        {
					if(_RoomID_W == null)
	        	    {
						_RoomID_W = TearOff.RoomID;
					}
					return _RoomID_W;
				}
			}

			public AggregateParameter Number
		    {
				get
		        {
					if(_Number_W == null)
	        	    {
						_Number_W = TearOff.Number;
					}
					return _Number_W;
				}
			}

			public AggregateParameter RoomCategoryID
		    {
				get
		        {
					if(_RoomCategoryID_W == null)
	        	    {
						_RoomCategoryID_W = TearOff.RoomCategoryID;
					}
					return _RoomCategoryID_W;
				}
			}

			public AggregateParameter Price
		    {
				get
		        {
					if(_Price_W == null)
	        	    {
						_Price_W = TearOff.Price;
					}
					return _Price_W;
				}
			}

			private AggregateParameter _RoomID_W = null;
			private AggregateParameter _Number_W = null;
			private AggregateParameter _RoomCategoryID_W = null;
			private AggregateParameter _Price_W = null;

			public void AggregateClauseReset()
			{
				_RoomID_W = null;
				_Number_W = null;
				_RoomCategoryID_W = null;
				_Price_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "InsertRoom]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.RoomID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "UpdateRoom]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "DeleteRoom]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.RoomID);
			p.SourceColumn = ColumnNames.RoomID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.RoomID);
			p.SourceColumn = ColumnNames.RoomID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Number);
			p.SourceColumn = ColumnNames.Number;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RoomCategoryID);
			p.SourceColumn = ColumnNames.RoomCategoryID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Price);
			p.SourceColumn = ColumnNames.Price;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
