
// Generated by MyGeneration Version # (1.3.0.3)

using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;
using VikkiSoft_BLL.DAL;

namespace VikkiSoft_BLL
{
	public class Gallery : _Gallery
	{
		public Gallery()
		{
		
		}

        public virtual bool LoadByCategoryID(int categoryID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@CategoryID", SqlDbType.Int), categoryID);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Gallery_LoadByCategoryID]", parameters);
        }

        public virtual void UpdateCoverByCategoryID(int categoryID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@CategoryID", SqlDbType.Int), categoryID);

            base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Gallery_UpdateCoverByCategoryID]", parameters);
        }

        public virtual bool LoadCoverByCategoryID(int categoryID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@CategoryID", SqlDbType.Int), categoryID);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Gallery_LoadCoverByCategoryID]", parameters);
        }

        public virtual bool LoadGallery()
        {
            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Gallery_LoadGallery]");
        }

        public virtual void Move(int categoryID, int sourceGalleryID, int destGalleryID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@CategoryID", SqlDbType.Int), categoryID);
            parameters.Add(new SqlParameter("@SourceGalleryID", SqlDbType.Int), sourceGalleryID);
            if (destGalleryID > 0)
            {
                parameters.Add(new SqlParameter("@DestGalleryID", SqlDbType.Int), destGalleryID);
            }

            base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Gallery_Move]", parameters);
        }
	}
}
