
// Generated by MyGeneration Version # (1.3.0.3)

using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;
using VikkiSoft_BLL.DAL;

namespace VikkiSoft_BLL
{
	public class Room : _Room
	{
		public Room()
		{
		
		}

        public virtual bool LoadWithRoomCategoty()
        {
            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Room_LoadWithRoomCategoty]");
        }

        public virtual bool LoadPriceByRoomCategoryID(int roomCategoryID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@RoomCategoryID", SqlDbType.Int), roomCategoryID);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Room_LoadPriceByRoomCategoryID]", parameters);
        }
	}
}
